spring:
  application:
    name: SpringDataJpaDocker
  datasource:
    url: jdbc:postgresql://localhost:5432/dockerVersion
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect